version: 1.3.0
services:
  - mysql
  - php:
      version: 7.3
events:
  build:
    steps:
        - setup-project:
            type: script
            script:
              - composer install
              